name: threeactions_area
description: Threeactions

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: "^3.4.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  url_launcher: ^6.2.1
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  fonts:
    - family: Teko
      fonts:
        - asset: fonts/Teko-Regular.ttf
          weight: 700
    - family: ApexLight
      fonts:
        - asset: fonts/Apex-Mk3-ExtraLight.otf
          weight: 700
    - family: ApexMedium
      fonts:
        - asset: fonts/Apex-Mk3-Medium.otf
          weight: 700
    - family: LackRegular
      fonts:
        - asset: fonts/Lack-Regular.otf
          weight: 700
    - family: LackRegularLine
      fonts:
        - asset: fonts/Lack-Line-Regular.otf
          weight: 700 
    - family: EBENYA
      fonts:
        - asset: fonts/EBENYA.ttf
          weight: 700
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/img/button_bg_skills.png
    - assets/img/button_bg_art.png
    - assets/img/button_bg_bio.png
    - assets/img/button_bg_contacts.png
    - assets/img/logo_skills.png
    - assets/img/logo_skills_big.png
    - assets/img/logo_skills_base.png
    - assets/img/logo_skills_part.png
    - assets/img/logo_art.png
    - assets/img/logo_art_big.png
    - assets/img/logo_art_base.png
    - assets/img/logo_art_part_bottom.png
    - assets/img/logo_art_part_top.png
    - assets/img/logo_bio.png
    - assets/img/logo_bio_big.png
    - assets/img/logo_bio_base.png
    - assets/img/logo_bio_part.png
    - assets/img/logo_contacts.png
    - assets/img/logo_contacts_big.png
    - assets/img/logo_contacts_base.png
    - assets/img/logo_contacts_part_top.png
    - assets/img/logo_contacts_part_bottom.png
