name: "Web - Build and Publish"
on:
  push:
    branches:
    - main
jobs:
  build-and-deploy:
    name: Build Web
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable

    - name: Configure Flutter for web
      shell: bash
      run: |
        flutter config --enable-web
        flutter create --platforms=web .

    - name: Build the Flutter web application
      shell: bash
      run: |
        flutter pub get
        flutter build web --release --base-href "/ThreeactionsArea/"

    - name: Configure Git
      shell: bash
      run: |
        git config --global user.name "GreyLabsDev"
        git config --global user.email "greyson.dean@gmail.com"
        git config --global --add safe.directory /github/workspace

    - name: Deploy to GitHub pages
      shell: bash
      run: |
        git add build/web/ -f
        git commit -m "Deploy Flutter Web Application"
        git push origin $(git subtree split --prefix=build/web/):gh-pages -f